AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

# Rubocop defaults to 120 now - that's a bit too wide for me.
Layout/LineLength:
  Max: 100

# Disabled cops

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
