plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-sequel

AllCops:
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

# Disabled cops

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
