glossary:
  1B:
    title: Singles
    description: Number of singles.

  2B:
    title: Doubles
    description: Number of doubles.

  3B:
    title: Triples
    description: Number of triples.

  AB:
    title: At Bats
    description: >
      Number of trips to the plate in which the batter does not walk, get hit by
      a pitch, sacrifice (fly or bunt), or reach on interference.

  AVG:
    title: Batting Average
    description: Rate of hits per at bat, calculated as H/AB.
    see_also:
      - H
      - AB

  BABIP:
    title: Batting Average on Balls in Play
    description: >
      The rate at which the batter gets a hit when he puts the ball in play,
      calculated as (H-HR)/(AB-K-HR+SF).
    link: http://www.fangraphs.com/library/offense/babip/
    see_also:
      - H
      - HR
      - AB
      - K
      - SF

  BB:
    title: Walks
    description: Total number of walks (includes IBB).

  BB%:
    title: Walk Percentage
    description: >
      Frequency with which the batter has walked, calculated as walks divided by
      plate appearances.
    link: http://www.fangraphs.com/library/offense/rate-stats/

  BB/K:
    title: Walk to Strikeout Rate
    description: Ratio of walks to strikeouts, calculated as Walks/Strikeouts.

  BsR:
    title: Base Running Runs Above Average
    description: >
      Number of runs above or below average a player has been worth on the
      bases, based on stolen bases, caught stealing, extra bases taken, outs on
      the bases, and avoiding double plays. It is the combination of wSB, UBR,
      and wGDP.
    link: http://www.fangraphs.com/library/offense/bsr/
    see_also:
      - wSB
      - UBR
      - wGDP

  BUH:
    title: Bunt Hits
    description: Number of bunt hits.

  BUH%:
    title: Bunt Hit Percentage
    description: >
      Percentage of bunts that go for hits, calculated as Bunt Hits/Bunts.

  Cent%:
    title: Center Percentage
    description: Percentage of batted balls hit to the middle of the field.
    link: http://www.fangraphs.com/library/offense/batted-ball-direction/
    see_also:
      - Pull%
      - Oppo%

  Clutch:
    title: Clutch Score
    description: >
      The difference between a player's total WPA/pLI and their WPA/LI.
    link: http://www.fangraphs.com/library/misc/clutch/
    see_also:
      - WPA/pLI
      - WPA
      - LI

  Contact%:
    title: Contact Percentage
    description: Contact made divided by swings.
    link: http://www.fangraphs.com/library/offense/plate-discipline/

  CS:
    title: Caught Stealing
    description: Number of times caught stealing.

  Def:
    title: Defensive Runs Above Average
    description: >
      Number of runs above or below average a player has been worth on defense,
      combining Fielding Runs (Total Zone before 2002, UZR after) and the
      positional adjustment.
    link: http://www.fangraphs.com/library/defense/def/
    see_also:
      - "Off"

  FB%:
    title: Fly Ball Percentage
    description: >
      The percentage of a batter's balls in play that are fly balls, calculated
      as FB/BIP.
    link: http://www.fangraphs.com/library/offense/batted-ball/

  F-Strike%:
    title: First Pitch Strike Percentage
    description: Percentage of PA that begin with a strike.
    link: http://www.fangraphs.com/library/offense/plate-discipline/

  G:
    title: Games Played
    description: Number of games in which the player has appeared.

  GB/FB:
    title: Ground Ball to Fly Ball Ratio
    description: >
      The ratio of ground balls a batter hits to fly balls, calculated as GB/FB.

  GB%:
    title: Ground Ball Percentage
    description: >
      The percentage of a batter's balls in play that are ground balls,
      calculated as GB/BIP.
    link: http://www.fangraphs.com/library/offense/batted-ball/

  GDP:
    title: Grounded into Double Play
    description: Number of times the batter hit into a double play.

  H:
    title: Hits
    description: Number of hits.

  Hard%:
    title: Hard Contact Percentage
    description: Percentage of hard-hit batted balls.
    link: http://www.fangraphs.com/library/offense/quality-of-contact-stats/
    see_also:
      - Soft%
      - Med%

  HBP:
    title: Hit By Pitches
    description: Number of times the batter reached after being hit by a pitch.

  HR:
    title: Home Runs
    description: Number of home runs.

  HR/FB:
    title: Home Run to Fly Ball Rate
    description: >
      Percentage of a batter's fly balls that go for home runs, calculated as
      HB/FB (even though some HR are line drives).
    see_also:
      - HR
      - FB

  IBB:
    title: Intentional Walks
    description: Number of times the batter was intentionally walked.

  IFFB%:
    title: Infield Fly Ball Percentage
    description: >
      Percentage of a batter's fly balls that were infield fly balls, calculated
      as IFFB/FB.
    see_also:
      - IFFB
      - FB

  IFH:
    title: Infield Hits
    description: Number of infield hits.

  IFH%:
    title: Infield Hit Percentage
    description: >
      Percentage of ground balls that are infield hits, calculated as IFH/GB.
    see_also:
      - IFH
      - GB

  ISO:
    title: Isolated Power
    description: >
      Average number of extra bases per at bat, calculated several ways such as
      SLG minus AVG.
    link: http://www.fangraphs.com/library/offense/iso/

  K%:
    title: Strikeout Percentage
    description: >
      Frequency with which the batter has struck out, calculated as strikeouts
      divided by plate appearances.
    link: http://www.fangraphs.com/library/offense/rate-stats/
  see_also:
    - K
    - PA

  LD%:
    title: Line Drive Percentage
    description: >
      The percentage of a batter's balls in play that are line drives,
      calculated as LD/BIP.
    link: http://www.fangraphs.com/library/offense/batted-ball/
  see_also:
    - LD
    - BIP

  Med%:
    title: Medium Contact Percentage
    description: Percentage of medium-hit batted balls.
    link: http://www.fangraphs.com/library/offense/quality-of-contact-stats/
    see_also:
      - Hard%
      - Soft%

  OBP:
    title: On Base Percentage
    description: >
      Rate at which the batter reaches base, calculated as
      (H+BB+HBP)/(AB+BB+HBP+SF).
    link: http://www.fangraphs.com/library/offense/obp/
    see_also:
      - H
      - BB
      - HBP
      - AB
      - SF

  O-Contact%:
    title: Outside the Zone Contact Percentage
    description: >
      Contact made outside the zone divided by swings outside the zone.
    link: http://www.fangraphs.com/library/offense/plate-discipline/

  "Off":
    title: Offensive Runs Above Average
    description: >
      Number of runs above or below average a player has been worth offensively,
      combining Batting Runs and BsR.
    link: http://www.fangraphs.com/library/offense/off/
    see_also:
      - Def

  Oppo%:
    title: Opposite Field Percentage
    description: Percentage of batted balls hit to the opposite field.
    link: http://www.fangraphs.com/library/offense/batted-ball-direction/
    see_also:
      - Pull%
      - Cent%

  OPS:
    title: On Base Plus Slugging
    description: Combination of OBP and SLG, calculated as OBP+SLG.

  O-Swing%:
    title: Outside the Zone Swing Percentage
    description: >
      Swings at pitches outside the zone divided by pitches outside the zone.
    link: http://www.fangraphs.com/library/offense/plate-discipline/

  PA:
    title: Plate Appearances
    description: Number of times the player has come to the plate.

  PH:
    title: Pinch Hits
    description: Number of hits while serving as a pinch hitter.

  phLI:
    title: Average Leverage Index while Pinch Hitting
    description: >
      The average leverage index of each batter's plate appearances while pinch
      hitting.
    link: http://www.fangraphs.com/library/misc/li/

  pLI:
    title: Average Leverage Index
    description: The average leverage index of each batter's plate appearances.
    link: http://www.fangraphs.com/library/misc/li/

  Pull%:
    title: Pull Percentage
    description: Percentage of batted balls hit to the pull field.
    link: http://www.fangraphs.com/library/offense/batted-ball-direction/
    see_also:
      - Cent%
      - Oppo%

  R:
    title: Runs Scored
    description: Number of runs scored.

  RBI:
    title: Runs Batted In
    description: >
      Number of times a run scores as a result of a batter's plate appearance,
      not counting situations in which an error caused the run to score or the
      batter hit into a double play.

  RE24:
    title: Run Expectancy 24 Base Out State
    description: >
      The total impact a batter's plate appearances (or SB/CS) have on his
      team's run expectancy relative to league average.
    link: http://www.fangraphs.com/library/misc/re24/
    see_also:
      - REW

  REW:
    title: Run Expectancy Wins
    description: RE24 converted from runs to wins.
    link: http://www.fangraphs.com/library/misc/re24/
    see_also:
      - RE24

  SB:
    title: Stolen Bases
    description: Number of stolen bases.

  SF:
    title: Sacrifice Flies
    description: >
      Number of times a batter's fly out allowed a runner to tag up and score.

  SH:
    title: Sacrifice Bunts
    description: >
      Any bunt in which there was a runner on base and less than two outs in
      which the batter was put out and at least one runner advanced.

  SLG:
    title: Slugging Percentage
    description: >
      Average number of total bases per at bat, calculated as Total Bases/AB.

  SO:
    title: Strikeouts
    description: Number of strikeouts.

  Soft%:
    title: Soft Contact Percentage
    description: Percentage of soft-hit batted balls.
    link: http://www.fangraphs.com/library/offense/quality-of-contact-stats/
    see_also:
      - Hard%
      - Med%

  Spd:
    title: Speed Score
    description: >
      A slightly outdated statistic that attempts to measure a player's running
      ability.

  Swing%:
    title: Swing Percentage
    description: Swings divided by total pitches.
    link: http://www.fangraphs.com/library/offense/plate-discipline/
    see_also:
      - SwStr%

  SwStr%:
    title: Swinging Strike Percentage
    description: Swinging strikes divided by total pitches.
    link: http://www.fangraphs.com/library/offense/plate-discipline/
    see_also:
      - Swing%

  UBR:
    title: Ultimate Base Running
    description: >
      The number of runs above or below average added by a player on all
      non-SB/CS base running players.

  WAR:
    title: Wins Above Replacement
    description: >
      A comprehensive statistic that estimates the number of wins a player has
      been worth to his team compared to a freely available player such as a
      minor league free agent.
    link: http://www.fangraphs.com/library/misc/war/

  wGDP:
    title: Weighted Grounded Into Double Play Runs
    description: >
      The number of runs above or below average added by a player by staying out
      of double plays.
    see_also:
      - gdp

  wOBA:
    title: Weighted On Base Average
    description: >
      Combines all the different aspects of hitting into one metric, weighting
      each of them in proportion to their actual run value. While batting
      average, on-base percentage, and slugging percentage fall short in
      accuracy and scope, wOBA measures and captures offensive value more
      accurately and comprehensively.
    link: http://www.fangraphs.com/library/offense/woba/

  WPA:
    title: Win Probability Added
    description: >
      The total impact a batter's plate appearances (or SB/CS) have on his
      team's win expectancy relative to league average.
    link: http://www.fangraphs.com/library/misc/wpa/
    see_also:
      - -WPA
      - +WPA
      - WPA/LI


  "-WPA":
    title: Negative Win Probability Added
    description: The sum of a batter's negative WPA events.
    link: http://www.fangraphs.com/library/misc/wpa/
    see_also:
      - WPA
      - +WPA
      - WPA/LI

  +WPA:
    title: Positive Win Probability Added
    description: The sum of a batter's positive WPA events.
    link: http://www.fangraphs.com/library/misc/wpa/
    see_also:
      - WPA
      - -WPA
      - WPA/LI

  WPA/LI:
    title: Situational Wins
    description: >
      A player's WPA controlling for leverage index, calculated as the sum of
      each event's WPA/LI, not total WPA/LI.
    link: http://www.fangraphs.com/library/misc/wpa-li/
    see_also:
      - WPA
      - -WPA
      - +WPA

  wRAA:
    title: Weighted Runs Above Average
    description: >
      Number of runs above or below average a player has added as a hitter.

  wRC:
    title: Weighted Runs Created
    description: >
      Number of runs a player has generated for his team as a result of his wOBA
      and playing time.
    link: http://www.fangraphs.com/library/offense/wrc/
    see_also:
      - wRC+

  wRC+:
    title: Weighted Runs Created Plus
    description: >
      The most comprehensive rate statistic used to measure hitting performance
      because it takes into account the varying weights of each offensive action
      (like wOBA) and then adjusts them for the park and league context in which
      they took place.
    link: http://www.fangraphs.com/library/offense/wrc/
    see_also: wRC

  wSB:
    title: Weighted Stolen Base Runs Above Average
    description: >
      Number of runs above or below average added by a player on stolen base
      attempts.

  Z-Contact%:
    title: Inside the Zone Contact Percentage
    description: Contact made inside the zone divided by swings inside the zone.
    link: http://www.fangraphs.com/library/offense/plate-discipline/

  Z-Swing%:
    title: Inside the Zone Swing Percentage
    description: >
      Swings at pitches inside the zone divided by pitches inside the zone.
    link: http://www.fangraphs.com/library/offense/plate-discipline/

  Zone%:
    title: Zone Percentage
    description: Pitches inside the zone divided by total pitches.
    link: http://www.fangraphs.com/library/offense/plate-discipline/
