108:
  - los angeles angels of anaheim
  - los angeles angels
  - la angels
  - angels
  - anaheim
  - ana
  - laaa
  - laa
  - cal
109:
  - arizona diamondbacks
  - diamondbacks
  - arizona
  - ari
  - az
  - dbacks
110:
  - baltimore orioles
  - orioles
  - baltimore
  - bal
111:
  - boston red sox
  - red sox
  - boston
  - bos
  - bosox
  - bo sox
112:
  - chicago cubs
  - cubs
  - chc
113:
  - cincinatti reds
  - cincinatti
  - reds
  - cin
114:
  - cleveland indians
  - indians
  - cleveland
  - cle
115:
  - colorado rockies
  - rockies
  - colorado
  - col
  - co
116:
  - detroit tigers
  - tigers
  - detroit
  - det
  - beisbolcats
117:
  - houston astros
  - astros
  - houston
  - hou
118:
  - kansas city royals
  - kc royals
  - royals
  - kansas city
  - kc
  - kcr
  - kansas
119:
  - los angeles dodgers
  - los angeles
  - la dodgers
  - dodgers
  - lad
  - la
  - bkn
  - brooklyn
120:
  - washington nationals
  - nationals
  - washington
  - wsh
  - was
  - dc
  - natinals
  - nats
  - mtl
  - montreal
  - expos
121:
  - new york mets
  - mets
  - nym
133:
  - oakland athletics
  - athletics
  - oakland
  - oak
  - as
  - oakland as
134:
  - pittsburgh pirates
  - pirates
  - pittsburgh
  - pittsburg
  - buccos
  - pit
135:
  - san diego padres
  - sd padres
  - padres
  - san diego
  - sd
  - sdp
136:
  - seattle mariners
  - mariners
  - seattle
  - sea
137:
  - san francisco giants
  - sf giants
  - giants
  - san francisco
  - san fran
  - gigantes
  - sfg
  - sf
138:
  - st louis cardinals
  - cardinals
  - stl
  - st louis
  - salad eaters
  - cards
139:
  - tampa bay rays
  - devil rays
  - rays
  - tampa bay
  - tbr
  - tb
140:
  - texas rangers
  - rangers
  - texas
  - tex
141:
  - toronto blue jays
  - blue jays
  - toronto
  - tor
  - bluejays
  - jays
  - canada
142:
  - minnesota twins
  - twins
  - minnesota
  - min
143:
  - philadelphia phillies
  - phillies
  - philadelphia
  - philly
  - phils
  - phi
144:
  - atlanta braves
  - braves
  - atlanta
  - atl
  - barves
145:
  - chicago white sox
  - white sox
  - cws
  - chw
  - chisox
  - chi sox
146:
  - miami marlins
  - marlins
  - miami
  - mia
  - florida
  - fla
147:
  - new york yankees
  - yankees
  - nyy
  - bronx bombers
158:
  - milwaukee brewers
  - brewers
  - milwaukee
  - mil
